import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const toggleLanguage = (lang) => {
    setLanguage(lang);
  };

  const value = {
    language,
    toggleLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export const translations = {
  en: {
    signIn: "Sign in",
    getStarted: "Get started",
    signOut: "Sign out",
    manage: "Manage",
    signInToAccount: "Sign in to your account",
    createNewAccount: "create a new account",
    continueWithGoogle: "Continue with Google",
    orContinueWithEmail: "Or continue with email",
    emailAddress: "Email address",
    password: "Password",
    signingIn: "Signing in...",
    welcomeBack: "Welcome back!",
    dontHaveAccount: "Don't have an account?",
    joinInventoro: "Join Inventoro",
    alreadyHaveAccount: "Already have an account?",
    signInHere: "Sign in here",
    orSignUpWithEmail: "Or sign up with email",
    confirmPassword: "Confirm Password",
    creatingAccount: "Creating account...",
    createAccount: "Create Account",
    byCreatingAccount: "By creating an account, you agree to our",
    termsOfService: "Terms of Service",
    and: "and",
    privacyPolicy: "Privacy Policy",
    myInventories: "My Inventories",
    newInventory: "New Inventory",
    createNewInventory: "Create New Inventory",
    inventoryName: "Inventory Name",
    description: "Description",
    addCustomFields: "Add Custom Fields",
    fieldConfiguration: "Field Configuration",
    dragToReorder: "Drag to reorder",
    createInventory: "Create Inventory",
    yourInventories: "Your Inventories",
    noInventories: "No inventories yet",
    createFirstInventory: "Create your first inventory to get started",
    fields: "fields",
    itemCreatedSuccess: "Item created successfully!",
    itemCreatedError: "Failed to create item",
    itemUpdatedSuccess: "Item updated successfully!",
    itemsDeletedSuccess: "Items deleted successfully!",
    itemsDeletedError: "Failed to delete items",
    confirmDeleteItems: "Are you sure you want to delete {count} item(s)?",
    confirmDeleteInventory: "Delete Inventory",
    inventoryDeletedSuccess: "Inventory deleted successfully",
    loadingInventory: "Loading inventory...",
    inventoryNotFound: "Inventory not found",
    itemsCount: "items",
    addNewItem: "Add New Item",
    editItem: "Edit Item",
    customIdOptional: "Custom ID (optional)",
    customIdPlaceholder: "Enter custom ID...",
    yes: "Yes",
    no: "No",
    creating: "Creating...",
    saving: "Saving...",
    createItem: "Create Item",
    saveChanges: "Save Changes",
    itemsSelected: "item(s) selected",
    deleting: "Deleting...",
    deleteSelected: "Delete Selected",
    items: "Items",
    searchItemsPlaceholder: "Search items...",
    customId: "Custom ID",
    noItemsFound: "No items found",
    openLink: "Open Link",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    required: "is required",
    invalidEmail: "Email is invalid",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    open: "Open",
    public: "Public",
    private: "Private",
    more: "more",
    visibility: "Visibility",
    visibilityPublic: "Public (Visible to all)",
    visibilityPrivate: "Private (Only for you)",
    settings: "Settings",
    editInventory: "Edit Inventory",
    inventoryUpdatedSuccess: "Inventory updated successfully!",
    areYouSure: "Are you sure you want to delete",
    cannotBeUndone: "This action cannot be undone.",
    publicInventories: "Public Inventories",
    noPublicInventories: "No Public Inventories Found",
    checkBackLater: "Check back later or create your own!",
    readOnly: "Read Only",
  },
  ru: {
    signIn: "Войти",
    getStarted: "Начать",
    signOut: "Выйти",
    manage: "Управлять",
    signInToAccount: "Войдите в свой аккаунт",
    createNewAccount: "создать новый аккаунт",
    continueWithGoogle: "Продолжить с Google",
    orContinueWithEmail: "Или войти с email",
    emailAddress: "Email адрес",
    password: "Пароль",
    signingIn: "Вход...",
    welcomeBack: "С возвращением!",
    dontHaveAccount: "Нет аккаунта?",
    joinInventoro: "Присоединяйтесь к Inventoro",
    alreadyHaveAccount: "Уже есть аккаунт?",
    signInHere: "Войдите здесь",
    orSignUpWithEmail: "Или зарегистрируйтесь с email",
    confirmPassword: "Подтвердите пароль",
    creatingAccount: "Создание аккаунта...",
    createAccount: "Создать аккаунт",
    byCreatingAccount: "Создавая аккаунт, вы соглашаетесь с нашими",
    termsOfService: "Условиями обслуживания",
    and: "и",
    privacyPolicy: "Политикой конфиденциальности",
    myInventories: "Мои инвентари",
    newInventory: "Новый инвентарь",
    createNewInventory: "Создать новый инвентарь",
    inventoryName: "Название инвентаря",
    description: "Описание",
    addCustomFields: "Добавить поля",
    fieldConfiguration: "Настройка полей",
    dragToReorder: "Перетащите для изменения порядка",
    createInventory: "Создать инвентарь",
    yourInventories: "Ваши инвентари",
    noInventories: "Инвентарей пока нет",
    createFirstInventory: "Создайте первый инвентарь чтобы начать",
    fields: "поля",
    itemCreatedSuccess: "Элемент успешно создан!",
    itemCreatedError: "Ошибка создания элемента",
    itemUpdatedSuccess: "Элемент успешно обновлен!",
    itemsDeletedSuccess: "Элементы успешно удалены!",
    itemsDeletedError: "Ошибка удаления элементов",
    confirmDeleteItems: "Вы уверены, что хотите удалить {count} эл-т(ов)?",
    confirmDeleteInventory: "Удалить инвентарь",
    inventoryDeletedSuccess: "Инвентарь успешно удален",
    loadingInventory: "Загрузка инвентаря...",
    inventoryNotFound: "Инвентарь не найден",
    itemsCount: "эл-тов",
    addNewItem: "Добавить новый элемент",
    editItem: "Редактировать элемент",
    customIdOptional: "Свой ID (необязательно)",
    customIdPlaceholder: "Введите свой ID...",
    yes: "Да",
    no: "Нет",
    creating: "Создание...",
    saving: "Сохранение...",
    createItem: "Создать элемент",
    saveChanges: "Сохранить изменения",
    itemsSelected: "выбрано",
    deleting: "Удаление...",
    deleteSelected: "Удалить выбранное",
    items: "Элементы",
    searchItemsPlaceholder: "Поиск элементов...",
    customId: "Свой ID",
    noItemsFound: "Элементы не найдены",
    openLink: "Открыть ссылку",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успех",
    required: "обязателен",
    invalidEmail: "Неверный email",
    cancel: "Отмена",
    edit: "Редактировать",
    delete: "Удалить",
    open: "Открыть",
    public: "Публичный",
    private: "Приватный",
    more: "еще",
    visibility: "Видимость",
    visibilityPublic: "Публичный (Виден всем)",
    visibilityPrivate: "Приватный (Только для вас)",
    settings: "Настройки",
    editInventory: "Редактировать инвентарь",
    inventoryUpdatedSuccess: "Инвентарь успешно обновлен!",
    areYouSure: "Вы уверены, что хотите удалить",
    cannotBeUndone: "Это действие необратимо.",
    publicInventories: "Публичные инвентари",
    noPublicInventories: "Публичные инвентари не найдены",
    checkBackLater: "Загляните позже или создайте свой собственный!",
    readOnly: "Только для чтения",
  },
};
